// TODO: Include packages needed for this application
//i need inquirer to read inputs
//i need fs to write the file
const fs = require('fs');
const inquirer = require('inquirer');
//i need the markdown file
const markDown = require('./utils/generateMarkdown.js')
//this is only the markdown maker

// TODO: Create an array of questions for user input
//THEN a high-quality, professional README.md is generated with the title of my project and sections entitled Description, Table of Contents, Installation, Usage, License, Contributing, Tests, and Questions
//prompt for info
    //info needs :title, 
    //generate sections to store data: Description, ToC, Indtallation, usage, liscense, contributers, tests, and questions
    //Questions include github and email info
//ToC is autogenerated
const questions = ["What is the title of your project?", "Please write a description of your project.",  "How do you install your program?", 
    "How do you use your program?", "What are the liscenses on your project?", "How would someone contribute to this project?", "What are the testing instructions?",  
    "What is your GitHub username?", "What is your email address?"
];


// TODO: Create a function to write README file
//the write to file will be made last
function writeToFile(fileName, data) {
    fs.writeFile(fileName, data, (err) =>
        err ? console.log(err) : console.log("working")
    );
}

// TODO: Create a function to initialize app
function init() {
    inquirer
        .prompt([
            {
                type: "input",
                message: questions[0],
                name: "title"
            },{
                type: "input",
                message: questions[1],
                name: "description"
            },
            {
                type: "input",
                message: questions[2],
                name: "install"
            },
            {
                type: "input",
                message: questions[3],
                name: "use"
            },
            {
                type: "input",
                message: questions[4],
                name: "liscenses"
            },
            {
                type: "input",
                message: questions[5],
                name: "contribution"
            },
            {
                type: "input",
                message: questions[6],
                name: "testing"
            },
            {
                type: "input",
                message: questions[7],
                name: "gitHub"
            },
            {
                type: "input",
                message: questions[8],
                name: "email"
            },
        ])
        .then( function(response){
            console.log(response);
            //the response is an object with all the components
            const generatedReadMe = markDown(response);
            console.log(generatedReadMe);
            writeToFile('./storage/README.md', generatedReadMe);
        })

}

// Function call to initialize app
init();
